# Generated by Django 5.2.1 on 2025-06-13 02:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre requeridp')),
                ('typeProduct', models.CharField(max_length=100)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='cantidad de producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.91')), django.core.validators.MaxValueValidator(Decimal('9999.99'))], verbose_name='precio producto')),
            ],
        ),
    ]
