# Generated by Django 5.2.1 on 2025-05-30 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=200)),
                ('addres', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Ingresa email valido', max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='el numero debe tener entre 9 y 15 digitos', regex='^\\+?\\d{9,15}$')], verbose_name='Numero de Telefono')),
            ],
        ),
    ]
